// Generated by LiveScript 1.3.1
(function(){
  describe('Spore', function(x){
    beforeAll(function(done){
      var base_url;
      jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;
      this.routeGetList = void 8;
      this.routePost = void 8;
      this.routeGetOne = void 8;
      this.routeDeleteOne = void 8;
      return this.client = new Spore('/base/data/description.json', function(){
        return done();
      }, base_url = 'http://localhost:3000/api');
    });
    return describe('Test client', function(x){
      it('initialize Spore client', function(){
        return expect(this.client.isReady).toBe(true);
      });
      it('log basic infos', function(){
        this.client.logBasicInfos();
        return expect(true).toBe(true);
      });
      it('check client base attrs', function(){
        expect(this.client.url).toBe('/base/data/description.json');
        expect(this.client.baseUrl).toBe('http://localhost:3000/api');
        return expect(this.client.description.name).toBe('TEST API');
      });
      it('check client method specs', function(){
        return expect(this.client.methodsSpecs.add_product != null).toBe(true);
      });
      describe('No token', function(x){
        beforeAll(function(done){
          var this$ = this;
          return this.client.methods.add_product({
            payload: {
              name: "voiture",
              sku: "206",
              price: 10000
            }
          }, function(response){
            this$.routePost = response;
            return done();
          });
        });
        return it('No token add product', function(){
          return expect(this.routePost.error).toEqual("No credentials sent!");
        });
      });
      describe('Wrong token', function(x){
        beforeAll(function(done){
          var this$ = this;
          this.client.enable(SporeMiddlewareAuthApiKey, {
            key_name: "Authorization",
            key_value: "Token WRONG"
          });
          return this.client.methods.add_product({
            payload: {
              name: "voiture",
              sku: "206",
              price: 10000
            }
          }, function(response){
            this$.routePost = response;
            return done();
          });
        });
        return it('No token add product', function(){
          return expect(this.routePost.error).toEqual("Wrong token");
        });
      });
      it('enable middleware', function(){
        this.client.enable(SporeMiddlewareAuthApiKey, {
          key_name: "Authorization",
          key_value: "Token S3CR3T"
        });
        expect(this.client.middlewares[1].middlewareClass.name).toBe("SporeMiddlewareAuthApiKey");
        expect(this.client.middlewares[1].params.key_name).toBe("Authorization");
        return expect(this.client.middlewares[1].params.key_value).toBe("Token S3CR3T");
      });
      return describe('Test add product', function(x){
        beforeAll(function(done){
          var this$ = this;
          return this.client.methods.add_product({
            payload: {
              name: "voiture",
              sku: "206",
              price: 10000
            }
          }, function(response){
            this$.routePost = response;
            return done();
          });
        });
        it('add product', function(){
          expect(this.routePost.name).toEqual("voiture");
          expect(this.routePost.sku).toEqual("206");
          return expect(this.routePost.price).toEqual(10000);
        });
        describe('Test get products', function(x){
          beforeAll(function(done){
            var this$ = this;
            return this.client.methods.get_products({
              name: "voiture"
            }, function(response){
              this$.routeGetList = response;
              return done();
            });
          });
          return it('get products', function(){
            expect(this.routeGetList.length).toBeGreaterThan(0);
            expect(this.routeGetList[0].name).toEqual("voiture");
            expect(this.routeGetList[0].sku).toEqual("206");
            return expect(this.routeGetList[0].price).toEqual(10000);
          });
        });
        describe('Test get one product', function(x){
          beforeAll(function(done){
            var this$ = this;
            return this.client.methods.get_product({
              id: this.routePost._id
            }, function(response){
              this$.routeGetOne = response;
              return done();
            });
          });
          return it('get one product', function(){
            expect(this.routeGetOne.name).toEqual("voiture");
            expect(this.routeGetOne.sku).toEqual("206");
            return expect(this.routeGetOne.price).toEqual(10000);
          });
        });
        return describe('Test delete product', function(x){
          beforeAll(function(done){
            var this$ = this;
            return this.client.methods.delete_product({
              id: this.routePost._id
            }, function(response){
              this$.routeDeleteOne = response;
              return done();
            });
          });
          return it('delete one product', function(){
            return expect(this.routeDeleteOne).toEqual("");
          });
        });
      });
    });
  });
}).call(this);
